geodjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from google_site_verification import GOOGLE_SITE_VERIFICATION_URL
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

from naturwb.urls import urlpatterns

# from dashboard.views import dashboard_view

urlpatterns = [
    path('admin/', admin.site.urls),
    GOOGLE_SITE_VERIFICATION_URL,
    path("", include("naturwb.urls")),
    path("favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("favicon.ico"))
    ),
]

naturwb/urls.py
from django.urls import path
from django.views.generic.base import TemplateView
from django.contrib.sitemaps.views import sitemap

from .views import (
    get_ref_view,
    home_view,
    result_view,
    method_view,
    impressum_view,
    result_download,
    datenschutz_view
    )
from .sitemaps import StaticViewSitemap

# from dashboard.views import dashboard_view

urlpatterns = [
    path('', home_view, name="home"),
    path('get_ref/', get_ref_view, name='get_reference'),
    path('get_ref/result/', result_view, name='Ergebnis der NatUrWB Referenz'),
    path('download_result/', result_download, name='download_result'),
    path('method/', method_view, name='method'),
    path('impressum/', impressum_view, name="impressum"),
    path('datenschutz/', datenschutz_view, name="datenschutz"),
    path("robots.txt",
         TemplateView.as_view(template_name="robots.txt",
                              content_type="text/plain")),
    path("sitemap.xml", sitemap,
         {"sitemaps": {
            'main': StaticViewSitemap
            }
         },
         name="django.contrib.sitemaps.views.sitemap",
)
]

naturwb/forms.py
from django import forms
from django.contrib.gis import forms as gforms
from leaflet.forms.fields import MultiPolygonField
from leaflet.forms.widgets import LeafletWidget


# only if saved to database
# class EnterPolygonForm(forms.ModelForm):
#     class Meta:
#         model = SearchPolygon
#         fields = [
#             'geom',
#             'name'
#             ]

class SearchPolygonQuery(forms.Form):
    search_query = forms.CharField(required=False, label="Suche nach einer Stadt ")

            
class EnterPolygonForm(gforms.Form):
    geom = MultiPolygonField(
        required=True, initial=None,
        widget=LeafletWidget(
            attrs={
                'map_width': "100%", 
                'map_height': "550px",
                'settings_overrides': {
                    #'DEFAULT_CENTER': (51.351, 10.459),
                    #'DEFAULT_ZOOM': 6,
                    'SPATIAL_EXTENT': (5.2,47.0,15.5,55.2)
                    }
                }),
        label=""
        )
    # standard geodjango library, does work, but no possibility to delete points
    # geom2 = gforms.PolygonField(required=True, label="", initial=None,
    #     widget= gforms.OSMWidget(attrs={
    #         'map_width': "100%", 
    #         'map_height': 800,
    #         'default_lat': 51.351,
    #         'default_lon': 10.459,
    #         'default_zoom': 6
    #         }))

naturwb/views.py
from django.shortcuts import render
from .forms import EnterPolygonForm
from django.contrib.gis.geos import GEOSGeometry
from aldjemy.core import get_engine
from .functions.geometry import geoencode
from .functions.naturwb import Query as NWBQuery
from shapely.wkt import loads as wkt_loads
import traceback
from django.shortcuts import redirect
from .models import NaturwbSettings, CachedResults
from .functions.naturwb_db import results_to_db
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.http import require_POST
import geopandas as gpd
import pandas as pd

# for result_download
import tempfile
from pathlib import Path
import zipfile
from django.http import StreamingHttpResponse
from django.core.files import File
import io
import datetime
import textwrap
from geodjango.settings import DEBUG


class Wartungsmodus:
    @property
    def state(self):
        return NaturwbSettings.objects.get(pk="Wartungsmodus").value

context_base = {
    'wartungsmodus': Wartungsmodus(),
    'debug': DEBUG}

APP_DIR = Path(__file__).parent
with open(APP_DIR.joinpath("data/README-part-Input.txt"), encoding="iso-8859-1") as f:
    README_PART_INPUT = f.read()
with open(APP_DIR.joinpath("data/README-part-results.txt"), encoding="iso-8859-1") as f:
    README_PART_RESULT = f.read()

# Create your views here.
def get_ref_view(request, *args, **kwargs):
    initial_data = {"geom": None}
    context = {
        "error_biggeom": False,
        'error_nogeom': False,
        **context_base
    }

    # check if it was redirected because of missing geom
    if "error_nogeom" in request.GET:
        context.update({"error_nogeom": bool(request.GET["error_nogeom"])})

    # check if it was redirected because of geom that was too big
    if "error_biggeom" in request.GET:
        context.update({"error_biggeom": bool(request.GET["error_biggeom"])})

    # do the city query if given and set initial data
    if "search_query" in request.GET:
        try:
            geom = geoencode(request.GET["search_query"])
            initial_data["geom"] = str(geom)
        except Exception as ex:
            print(ex)
            print(traceback.format_exc())
            context.update({
                "error_geoencoding": True,
                "search_query_name": request.GET["search_query"]})

    context.update({
        'poly_form': EnterPolygonForm(None, initial=initial_data)})

    return render(request, "get_ref.html", context)

@csrf_protect
@require_POST
def result_view(request, *args, **kwargs):
    # check for empty geom
    if 'geom' not in request.POST:
        return redirect("/get_ref/?error_nogeom=True")

    urban_geom = GEOSGeometry(request.POST['geom'], 4326)

    # check size
    if urban_geom.transform(25832, True).area > 1e9:
        return redirect("/get_ref/?error_biggeom=True")

    # make naturwb query
    try:
        nwbquery = NWBQuery(
            urban_shp=wkt_loads(urban_geom.wkt),
            db_engine=get_engine(),
            do_plots=False)

        context = {
            "messages": nwbquery.msgs,
            "success": True,
            "plot_sim_shps_clip_plotly": nwbquery.plot_web("sim_shps_clip_plotly"),
            # "plot_pie": nwbquery.plot_web("pie", figsize=(7, 7)),
            "plot_pie_plotly": nwbquery.plot_web("pie_plotly"),
            "plot_sankey": nwbquery.plot_web("sankey", figsize=(17,17), cex=1.5),
            "plot_ternary": nwbquery.plot_web("ternary", width=1000, do_size=True),
            "plot_pie_lanu": nwbquery.plot_web("pie_landuse"),
            "et_rel": "{:.0%}".format(nwbquery.naturwb_ref["et_rel"]).replace('%', ' %'),
            "a_rel": "{:.0%}".format(nwbquery.naturwb_ref["runoff_rel"]).replace('%', ' %'),
            "tp_rel": "{:.0%}".format(nwbquery.naturwb_ref["tp_rel"]).replace('%', ' %'),
            "n_natids": len(nwbquery.sim_shps_clip.index.get_level_values("nat_id").unique()),
            "urban_geom": request.POST['geom'],
            "cached": False,
            **context_base
            }

    except Exception as ex:
        print(ex)
        print(traceback.format_exc())
        context = {
            "success": False,
            **context_base
        }
        return render(request, "result.html", context)

    # save the results to DB
    try:
        # save the landuse results to the database
        try:
            if NaturwbSettings.objects.get(pk="save_to_db").value:
                results_to_db(nwbquery)
        except NaturwbSettings.DoesNotExist:
            print("No setting parameter 'save_to_db' in the naturwb_settings table in the database")

        # save the results to the caching table in the database
        if NaturwbSettings.objects.get(pk="cache_result_to_db"):
            cache = CachedResults.objects.create_cache(
                results_genid=nwbquery.get_results_genid(),
                stat_ids=nwbquery.sim_infos["stat_id"].unique(),
                messages=nwbquery.msgs
            )
            context.update({"cache_uuid": cache.uuid, "cached":True})
    except Exception as ex:
        print(ex)
        print(traceback.format_exc())

    return render(request, "result.html", context)

@csrf_protect
@require_POST
def result_download(request, *args, **kwargs):
    # get results from cache
    try:
        if "cache_uuid" in request.POST:
            res_gen, stat_ids, msgs = CachedResults.objects.get_cache(
                uuid=request.POST["cache_uuid"])
        else:
            raise Exception("No Cache found")
    except:
        if "urban_geom" in request.POST:
            urban_geom = GEOSGeometry(request.POST['urban_geom'])
            nwbquery = NWBQuery(
                urban_shp=wkt_loads(urban_geom.wkt),
                db_engine=get_engine(),
                do_plots=False)
            res_gen = nwbquery.get_results_genid()
            stat_ids = nwbquery.sim_infos["stat_id"].unique()
            msgs = nwbquery.msgs

    # wrap messages
    new_msgs = []
    wrapper = textwrap.TextWrapper(width=150)
    for msg in msgs:
        new_msgs.append(" - " + "\n   ".join(wrapper.wrap(msg)))

    # create README.txt
    with tempfile.TemporaryDirectory() as tmp_dir:
        # create results shape file
        tmp_dir_fp = Path(tmp_dir).joinpath("temp")
        tmp_dir_fp.mkdir()
        if "add_result" in request.POST:
            res_gen.to_file(tmp_dir_fp.joinpath("results.shp"))

        # create input files
        if "add_input" in request.POST:
            sim_ids = res_gen.index.get_level_values("sim_id").unique().astype(str)
            sim_in_dir = tmp_dir_fp.joinpath("input")
            sim_in_dir.mkdir()
            simids_sql_where = f"WHERE sim_id IN ({', '.join(sim_ids)})"
            gpd.read_postgis(
                f"SELECT sim_id, geom FROM tbl_simulation_polygons {simids_sql_where};",
                con=get_engine(),
                crs=25832,
                geom_col="geom"
            ).to_file(sim_in_dir.joinpath("Modellgebiete.shp"))

            pd.read_sql(
                f"SELECT * FROM view_simulation_paras {simids_sql_where};",
                con=get_engine()
            ).to_csv(sim_in_dir.joinpath("Simulations-Parameter.csv"),
                     index=False)

        # create zip file localy/memory
        if len(res_gen) > 500:
            zip_obj = Path(tmp_dir).joinpath("temp.zip")
        else:
            zip_obj = io.BytesIO()

        with zipfile.ZipFile(zip_obj, "a", zipfile.ZIP_DEFLATED, False) as zip_file:
            for folder in tmp_dir_fp.glob("**"):
                zip_file.write(folder, folder.relative_to(tmp_dir_fp))
                for file in folder.iterdir():
                    if file.is_file():
                        zip_file.write(file, file.relative_to(tmp_dir_fp))

            # add weather
            if "add_weather" in request.POST:
                wea_zip_dir = APP_DIR.joinpath("data/weather_zips/")
                zip_file.write(wea_zip_dir, "weather_stations")
                for stid in stat_ids:
                    zip_file.write(wea_zip_dir.joinpath(f"{stid}.zip"),
                                   f"weather_stations/{stid}.zip")

            # create README.txt
            readme = (
                "# README  #\n###########\n" +
                "Diese Datei soll das Ergebnis etwas erläutern und beschreiben.\n\n")
            if "add_input" in request.POST:
                readme += README_PART_INPUT
            if "add_weather" in request.POST:
                readme += (
                    "\n# /weather_stations/\n###################\n" +
                    "Im Ordner \"weather_stations\" befinden sich die einzelnen Stations-Zeitreihen die bei der Simulation für dieses Gebiet genutzt wurden.\n" +
                    "Je Station befindet sich hierin eine ZIP-Datei die nach der DWD-Stations-ID benannt ist. \n" +
                    "Darin befinden sich die 3 Zeitreihen für Niederschlag (N), Temperatur (Ta) und Evapotranspiration(ET)\n")
            if "add_result" in request.POST:
                readme += README_PART_RESULT
            if len(msgs)>0:
                readme += (
                    "\n\n##############\n# !!Achtung!! #\n##############\n"+
                    "Um eine NatUrWB-Referenz für ihr Gebiet zu erhalten, musste an einigen Punkten vom optimalen Weg abgewichen werden.\n"+
                    "Daher sind die Ergebnisse nur unter Berücksichtigung der folgenden Anmerkungen zu verstehen: \n" +
                    "\n".join(new_msgs))

            # store README to zip
            zip_file.writestr("README.txt", readme.encode("iso-8859-1"))

        # create http response
        file_buffer = File(zip_obj)
        response = StreamingHttpResponse(file_buffer, content_type="application/zip")
        response['Content-Disposition'] = f'attachment; filename="result_{datetime.datetime.now().strftime("%Y-%m-%d_%H%M%S")}.zip"'
        # response['Content-Length'] = file_buffer.tell()

naturwb/templates/base.html
<!doctype html>
{% load static %}
<html lang="de">
<head>
  <title>NatUrWB</title>
  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
  <meta name="description" content="Ein interaktives Webtool zum bestimmen der naturnahen urbanen Wasserbilanz (NatUrWB) für ein beliebiges Gebiet in Deutschland als Referenzwert. Dieser Referenzwert beschreibt die Wasserbilanz eines Gebietes die sich einstellen würde, wenn keine Stadt vorhanden wäre.">

  <!-- OpenGraph protocol -->
  <meta property="og:title" content="NatUrWB"/>
  <meta property="og:type" content="Website"/>
  <meta property="og:description" content="Ein interaktives Webtool zum bestimmen der naturnahen urbanen Wasserbilanz (NatUrWB) für ein beliebiges Gebiet in Deutschland als Referenzwert. Dieser Referenzwert beschreibt die Wasserbilanz eines Gebietes die sich einstellen würde, wenn keine Stadt vorhanden wäre."/>
  <meta property="og:url" content="www.naturwb.de"/>
  <meta property="og:image" content="{{request.scheme}}://{{request.META.HTTP_HOST}}{% static 'Logo_OG_1200_630.png' %}"/>
  <meta property="og:image:type" content="image/png" />
  <meta property="og:image:alt" content="The NatUrWB-Logo" />
  <meta property="og:image:width" content="1200" />
  <meta property="og:image:height" content="630" />
  <meta property="og:image" content="{{request.scheme}}://{{request.META.HTTP_HOST}}{% static 'Logo_OG_638_630.png' %}"/>
  <meta property="og:image:type" content="image/png" />
  <meta property="og:image:alt" content="The NatUrWB-Logo" />
  <meta property="og:image:width" content="638" />
  <meta property="og:image:height" content="630" />
  <meta property="og:locale" content="de_DE" />

  {% block head_first %}{% endblock %}
  <!-- load bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">

  <!-- for mobile friendly views -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{% static "css/mobile-menu.css" %}">

  <!-- extra styles -->
  <link rel="stylesheet" href="{% static 'css/custom_base.css' %}">
  <link rel="stylesheet" href="{% static 'css/custom_bootstrap_primary.css' %}">

  {% block head %}{% endblock %}
</head>
{% block body_all %}
<body style="background-color: #F2F2F2;"> 
  <!-- Navigation Pane -->
  <div class="container-fluid sticky-top">
    <table class="header">
      <tr>
        <td>
          <a href="https://www.uni-freiburg.de/" target="_blank">
            <img src="{% static "img/ihf_header_left.gif" %}" height="165" border="0" align="left">
          </a>
        </td><td height="165" width="100%" style="position:relative;" >
          <img src="{% static "img/ihf_header_center.gif" %}" width="100%" height="165" border="0" style="position:absolute;top:0;">
          <div class="container pt-md-2 ps-0 pe-0 ps-md-2 pe-md-2 ps-sm-1 pe-sm-1" style="position:absolute;top:0;">
            <nav class="navbar navbar-expand-lg navbar-dark bg-primary navbar-toggler" style="z-index:100;">
              <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'home' %}">
                  <img type="image/png" src="{% static "Logo_header.png" %}" width="75px" height="75px" alt="The NatUrWB-Logo" class="d-none d-sm-inline">
                  <span class="align-middle" style="font-size:34px;">NatUrWB</span>
                </a>
              </div>
              <!-- Mobile Menu -->
              <button class="navbar-toggler second-button" type="button" data-bs-toggle="collapse"
                      data-bs-target="#menuitems" aria-controls="menuitems"
                      aria-expanded="false" aria-label="Toggle navigation">
                <div class="animated-icon2"><span></span><span></span><span></span><span></span></div>
              </button>

              <!-- App specific Menu -->
              <div class="navbar-collapse collapse" id="menuitems">
                <ul class="navbar-nav me-auto">
                  <li class="nav-item "><a href="{% url 'home' %}" class="nav-link">Home</a></li>
                  <li class="nav-item "><a href="{% url 'method' %}" class="nav-link">Methode</a></li>
                  <li class="nav-item "><a href="{% url 'get_reference' %}" class="nav-link">Referenz abfragen</a></li> 
                </ul>
              </div>
            {% if user.is_authenticated %}
            <!-- Login Information -->
            <ul class="nav navbar-nav">
              <li class="nav-item dropdown">
                {% block login_navbar %}
                  <a class="nav-link dropdown-toggle" href="#" id="navbarLoginDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="font-size:30px">
                    {% if user.is_authenticated %}{{ user.username }} {% endif %}<i class="bi bi-person-circle"></i>
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarLoginDropdown">
                      <a href="{% url 'admin:index' %}" class="dropdown-item">Admin</a>
                      <a href="{% url 'admin:logout' %}" class="dropdown-item">Log out</a>
                  </div>
                {% endblock login_navbar %}
              </li>
            </ul>
            {% endif %}
  
          </div>
        </nav>
        </td><td>
          <a href="https://www.hydro.uni-freiburg.de/" target="_parent" class="d-none d-md-inline">
            <img src="{% static "img/ihf_header_right.gif" %}" width="205" height="165" border="0"  align="right">
          </a>
        </td>
      </tr>
    </table>
  </div>

  <!-- Page content -->
  <div class="container shadow
              col-xl-9 col-lg-11 col-12
              pb-md-2 mb-md-4
              pt-md-2
              ps-0 pe-0 ps-md-2 pe-md-2 ps-sm-1 pe-sm-1"
       style="background-color: #FFFFFF;"
       id="main_page">
    <div class="container-fluid">
      {% if debug %}
        <div class="container-fluid alert alert-danger" role "alert">
          <h3>
            !!! This website is in debuging mode !!!
          </h3>
        </div>
      {% endif%}
      {% block unrelease_message %}{% endblock %}
      {% block content %}{% endblock %}
    </div>


    <!-- Footer -->
    <div class="col-auto d-inline-flex position-relative fixed-bottom"
          style="left:50%; transform: translate(-50%, 0%);">
      <a href="{% url 'impressum' %}" class="me-2">Impressum</a>
      <a href="{% url 'datenschutz' %}" class="me-2">Datenschutzerklärung</a> 
    </div>

    <div class="col-auto position-sticky
                d-inline-flex justify-content-end
                fixed-bottom
                " style="left:100%">
      &#169; HyFr - Max Schmit (2023)
    </div>
  </div>

  <!-- Skripte -->
  {% block scripts_first %}{% endblock %}

  <!-- load JQuery -->
  <script
  src="https://code.jquery.com/jquery-3.6.0.min.js"
  integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
  crossorigin="anonymous"></script>

  <!-- Bootstrap -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>

  <!-- Mobile view Navbar -->
  <script defer>
    let activate_navbar = () => {
      let path = document.location.href;
      let navitems = document.querySelectorAll("#menuitems > .navbar-nav > .nav-item > a");
      navitems.forEach((el) => {
        if (el.href==path){
          el.parentElement.classList.add('active')
        } else {
          el.parentElement.classList.remove('active')
        }
      })
    }
    activate_navbar()
    {% comment %} mobile button {% endcomment %}
    document.querySelector("button.second-button").addEventListener("click",
      ()=>{$('.animated-icon2').toggleClass('open');}
    )
  </script>

  {% block scripts %}{% endblock %}

</body>
{% endblock body_all %}

naturwb/templates/get_ref.html
{% extends 'base.html' %}
{% load static %}
{% load leaflet_tags %}

{% block head %}

    {% leaflet_js %}
    {% leaflet_css %}

    <style>
      .loading {
        display: none; 
        position: fixed; 
        left:50%;
        top:50%;
        transform: translate(-50%, -40%);
        z-index: 401;
        max-width: 80%;
        width: auto;
      };
    </style>

{% endblock %}

{% block content %}
  <div class="loading" id="loading">
    <img src="{%static "loading.gif" %}"> 
  </div>

  <h2>Bestimme einen NatUrWB-Referenzwert</h2>
  <p>Um die natürliche Wasserbilanz für ein urbanes Gebiet zu bestimmen, zeichnen Sie das Gebiet manuell ein, laden eine Datei rein oder verwendeten Sie die Suchfunktion (OpenStreetMap), um ein Stadtgebiet auszuwählen. Die mittels automatischer Suche ausgewählten Stadtgebiete können anschließend manuell editiert werden. 
  <br>Für dieses Gebiet wird dann ein NatUrWB-Referenzwert bestimmt.</p>
  <p>Das Gebiet kann eine bereits bebaute Fläche sein oder eine noch unbebaute Fläche, für die eine Bebauung geplant ist.</p>
  
  <div class="container-fluid pb-2">
    <p>Hier können Sie eine Fläche in Deutschland wählen, für die die NatUrWB-Referenz bestimmt werden soll:</p>
    <div class="container-fluid">
      <div class="row d-flex justify-content-end">
        <div class="col-md-auto col-12 ps-0 me-2">
          <input type="file" id="FileInput" accept=".zip" style="display:none"> 
          <button class="btn btn-primary" id="btnLoad" container="body" data-toggle="popover" data-bs-placement="top" data-bs-trigger="hover" title="Polygon laden" data-bs-content="Wenn Sie ihr eigenes Polygon laden wollen, geht das hierrüber.<br>Hierfür muss ihr Polygon in einer <b>ESRI-Shape-Datei</b> abgespeichert sein. Verpacken Sie diese anschließend in einen <b>ZIP-Ordner</b> und laden diesen hier hoch.<br>Diese Shape Datei soll nur aus einem einzigen (Multi)Polygon bestehen.">Datei laden...</button>
        </div>
        <form class="col-md-auto col-12 ms-auto me-0" action="#" id="geoencodeSearchForm"> 
          <label for="id_search_query">Suche nach einer Stadt: </label>
          <input type="text" name="search_query" id="id_search_query">                
          <input type="submit" value="Suche" class="btn btn-primary" id="btn_search_query">
          <div class="col-12 alert alert-danger p-1" id="error_search_query" hidden>
            <p class="m-0">Es konnte kein Polygon für ihre Eingabe gefunden werden.</p>
          </div>
        </form>
      </div>
    </div>
    {% if error_biggeom %}
      <div class="row justify-content-end mt-1">
        <div class="col-xl-8 col-lg-10 col-12 alert alert-danger">
          <p>
            Das eingegebene Polygon war zu groß. Das eingegebene Polygon darf maximal eine Fläche von 1.000 km<sup>2</sup> aufweisen.
          </p>
        </div>
      </div>
    {% endif %}

    {% if error_nogeom %}
      <div class="alert alert-danger">
        <p>
          Sie haben kein urbanes Gebiet ausgewählt um die Referenz zu bestimmen. Bitte wählen Sie auf der Karte ein Gebiet aus, für das die NatUrWB-Referenz bestimmt werden soll!
        </p>
      </div>
    {% endif %}

    <form action="./result/" method='post' name="get_ref"> 
      {% csrf_token %}
      {{ poly_form.as_p }}

      <div class="container-fluid d-inline-flex justify-content-end pe-0 me-0">
        <input type="submit" value="Berechne den Referenzwert" name="get_ref" class="btn btn-primary" onclick='myloading()' style="font-size: 20px; font-weight: 600;">
      </div>
    </form>
  </div>
{% endblock %}

{% block scripts_first %}
<!-- Popper -->
<script 
src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" 
integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" 
crossorigin="anonymous"></script>
{% endblock %}

{% block scripts %} 
  <script>
      function myloading() {
        document.getElementById("loading").style.display = "block";
      }
  </script>

  <!-- Scripts to load a zipped shapefile -->
  <script 
    src="https://unpkg.com/shpjs@4.0.2/dist/shp.js" 
    integrity="sha384-8zgYc0kN4QWlzKLwfrLam7F3/uCBlwDD8ac7ekzM8X3at8YLEfQHTcHJ99AOBr5l" 
    crossorigin="anonymous">
  </script>
  {% if debug %}
    <script src={% static "js/load-shp.js" %} defer></script>
    <script src={% static "js/geoencode.js" %} defer></script>
  {% else %}
    <script src={% static "js/load-shp.min.js" %} defer></script>
    <script src={% static "js/geoencode.min.js" %} defer></script>
  {% endif %}
  
  <!-- activate popover tooltips -->
  <script>
    $(document).ready(function () {
      $('[data-toggle="popover"]').popover(
        {html: true}
      );
    });
  </script>

  <!-- delete Circle Drawer -->
  <script>
    $(document).ready(function () {
      $('.leaflet-draw-draw-circlemarker').remove();
    });
  </script>
{% endblock %}